### ISSUE TITLE
I am trying to use this library with expo but react-native link command is not wokring at all

### ISSUE THREAD

**Issue by nandymandy1** [flyandi/react-native-maps-navigation#1]

**Comment by flyandi** [comment]
What is the error message? Can you post more information please. Also I never tested it with Expo. FYI.

**Comment by YuenEsc** [comment]
What I did to get it working with expo was take the files out from the library, then with expo Font I loaded the fonts (Navigation font, and the Akkurat), and it works, but what I found is that the simulate boolean doesn't change the behaviour of the Simulation, and it makes sense because when I researched more into the library, that value is useless.
I also have taken the example app, but the animations to the marker doesn't seems to work well, 
the zoom is not working. So I tried to change the animations functions to use animateCamera, but expo has maps version 0.22, so that method isn't included yet.

**Comment by dancomanlive** [comment]
Need to eject from Expo to use react-native link.

**Comment by flyandi** [comment]
I believe RN-maps requires the same and does not work directly with expo. So this lib will fall under the same principle.

**Comment by aaronbesson** [comment]
FYI, i got this working with Expo 33

**Comment by vrinch** [comment]
Hey @arronbesson, it would be really helpful if you can tell us how you got it working at all and especially with expo. It’s a great package as google doesn’t allow for such. A lot people cannot seem to get it working as shown in the gif.

Thanks
